name: arxiv-agent

volumes:
  postgres-data:
  tei-embedding-data:
  tei-reranker-data:

services:
  redis:
    image: redis:6
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 1s
      retries: 5
      
  postgres:
    image: pgvector/pgvector:pg16
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    env_file:
      - .env.production
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      start_period: 10s
      timeout: 1s
      retries: 5
      interval: 5s

  tei-embedding:
    # image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest # CPU (x86_64)
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-arm64-latest # CPU (aarch64)
    profiles: ["tei", "tei-embedding"]
    volumes:
      - tei-embedding-data:/data
    env_file:
      - .env.production
    entrypoint: ["/bin/sh", "-c"]
    command: ["exec text-embeddings-router --model-id \"$${EMBEDDING_MODEL}\""]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 300s

  tei-reranker:
    # image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest # CPU (x86_64)
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-arm64-latest # CPU (aarch64)
    profiles: ["tei", "tei-reranker"]
    volumes:
      - tei-reranker-data:/data
    env_file:
      - .env.production
    entrypoint: ["/bin/sh", "-c"]
    command: ["exec text-embeddings-router --model-id \"$${RERANKER_MODEL}\""]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 300s

  arxiv-agent:
    image: alimtegar/arxiv-agent:latest
    volumes:
      # Mount the source code into the container so changes don't require rebuilding the image
      - .:/deps/arxiv_agent
    ports:
      - "2024:8000"
    env_file:
      - .env.production
    environment:
      REDIS_URI: redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      tei-embedding:
        condition: service_healthy
      tei-reranker:
        condition: service_healthy