name: arxiv-agent-dev

volumes:
  tei-embedding-data:
  tei-reranker-data:

services:
  tei-embedding:
    # image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest # CPU (x86_64)
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-arm64-latest # CPU (aarch64)
    volumes:
      - tei-embedding-data:/data
    ports:
      - "8080:80"
    command: ["--model-id", "${EMBEDDING_MODEL}"] # EMBEDDING_MODEL is defined in .env
    
  tei-reranker:
    # image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest # CPU (x86_64)
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-arm64-latest # CPU (aarch64)
    volumes:
      - tei-reranker-data:/data
    ports:
      - "8081:80"
    command: ["--model-id", "${RERANKER_MODEL}"] # RERANKER_MODEL is defined in .env